services:
  postgresql:
    image: bitnami/postgresql:16.4.0
    environment:
      - POSTGRES_PASSWORD=12345678  # Variável de senha correta para o PostgreSQL
      - OS_NAME=linux
      - APP_VERSION=16.4.0
      - BITNAMI_APP_NAME=postgresql
    ports:
      - "5432:5432/tcp"  # Mapeamento de portas (evitar duplicatas)
