name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
        echo "DB_HOST=localhost" >> .env
        echo "DB_NAME=empresas" >> .env
        echo "DB_PORT=5432" >> .env
        echo "DB_USER=teste" >> .env
        echo "DB_PASSWORD=12345678" >> .env
        echo "TEST_CONNECTION=Host=localhost;Port=5432;Database=postgres;Username=postgres;Password=12345678;Include Error Detail=true;" >> .env

    - name: Set up Docker
      run: |
        echo "version: '3.8'" > docker-compose.yml
        echo "services:" >> docker-compose.yml
        echo "  postgresql:" >> docker-compose.yml
        echo "    image: bitnami/postgresql:16.4.0" >> docker-compose.yml
        echo "    environment:" >> docker-compose.yml
        echo "      - POSTGRES_PASSWORD=12345678" >> docker-compose.yml
        echo "    ports:" >> docker-compose.yml
        echo "      - '5432:5432'" >> docker-compose.yml
        docker compose up

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build and Test
      run: |
        dotnet restore
        dotnet build
        dotnet test

    - name: Stop and remove containers
      run: |
        docker compose down
