name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        docker run -d \
          --name postgresql \
          -e POSTGRES_PASSWORD=12345678 \
          -p 5432:5432 \
          bitnami/postgresql:16.4.0

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Create build script
      run: |
        echo '#!/bin/bash' > build.sh
        echo 'for project in $(find . -name '\''*.csproj'\'' | grep -v '\''Prosoft.Company.WF'\''); do' >> build.sh
        echo '    dotnet build "$project"' >> build.sh
        echo 'done' >> build.sh
        chmod +x build.sh

    - name: Build projects excluding Prosoft.Company.WF
      run: |
        ./build.sh

    - name: Create .env file in test output directory
      run: |
        mkdir -p tests/Prosoft.Company.Repositories.Tests/bin/Debug/net8.0 && \
        echo "DB_HOST=localhost" >> tests/Prosoft.Company.Repositories.Tests/bin/Debug/net8.0/.env && \
        echo "DB_NAME=empresas" >> tests/Prosoft.Company.Repositories.Tests/bin/Debug/net8.0/.env && \
        echo "DB_PORT=5432" >> tests/Prosoft.Company.Repositories.Tests/bin/Debug/net8.0/.env && \
        echo "DB_USER=teste" >> tests/Prosoft.Company.Repositories.Tests/bin/Debug/net8.0/.env && \
        echo "DB_PASSWORD=12345678" >> tests/Prosoft.Company.Repositories.Tests/bin/Debug/net8.0/.env && \
        echo "TEST_CONNECTION=Host=localhost;Port=5432;Database=postgres;Username=postgres;Password=12345678;Include Error Detail=true;" >> tests/Prosoft.Company.Repositories.Tests/bin/Debug/net8.0/.env

    - name: Run tests excluding Prosoft.Company.WF
      run: |
        for project in $(find . -name '*.csproj' | grep -v 'Prosoft.Company.WF'); do
            dotnet test "$project" --no-restore
        done

    - name: Stop and remove containers
      run: |
        docker stop postgresql
        docker rm postgresql
